server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #hostname: 3.144.211.167
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

